# Generated by Django 3.1.7 on 2021-04-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_publich_date',
            new_name='page_publish_date',
        ),
    ]
