# Generated by Django 3.1.7 on 2021-04-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comment',
        ),
    ]
